package project.entity;

public enum GameGenre {
    ACTION, ADVENTURE, ARCADE, SANDBOX, SURVIVAL, BATTLEROYALE, BOARD, CARD, CASINO, CASUAL, EDUCATIONAL, MUSIC, PUZZLE, RACING, SIMULATION, SPORTS, STRATEGY, TRIVIA, WORD;
}
